services:
  blaze:
    image: "samply/blaze:1.4@sha256:434988309af86cd1ba1d6f07603584495b6b8da4e4697875a4e90981912d2595"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx2g"
      DB_BLOCK_CACHE_SIZE: "2048"
      ENABLE_ADMIN_API: "true"
    ports:
    - "8080:8080"
    volumes:
    - "blaze-data:/app/data"

volumes:
  blaze-data:
